### ISSUE TITLE
数据库

### ISSUE THREAD

**Issue by Loliye** [970263611/boke#1]
请问有数据库文件嘛

**Comment by tBYTL** [comment]
这不是我写的，我只是收藏了一下。




------------------ 原始邮件 ------------------
发件人: "Loliye"<notifications@github.com>;
发送时间: 2019年9月9日(星期一) 上午9:29
收件人: "970263611/boke"<boke@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [970263611/boke] 数据库 (#1)




请问有数据库文件嘛

**Comment by 970263611** [comment]
这个是我写的，数据库文件在附件中，稍后我会上传上去




------------------ 原始邮件 ------------------
发件人: "qilong.sun"<notifications@github.com>;
发送时间: 2019年9月9日(星期一) 上午9:30
收件人: "970263611/boke"<boke@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [970263611/boke] 数据库 (#1)



这不是我写的，我只是收藏了一下。 
 
 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: "Loliye"<notifications@github.com>; 
 发送时间: 2019年9月9日(星期一) 上午9:29 
 收件人: "970263611/boke"<boke@noreply.github.com>; 
 抄送: "Subscribed"<subscribed@noreply.github.com>; 
 主题: [970263611/boke] 数据库 (#1) 
 
 
 
 
 请问有数据库文件嘛

**Comment by 970263611** [comment]
已经上传
